version: '3.7'

volumes:
  postgres-data-rpnhma:
    name: postgres-data-rpnhma
    driver: local

networks:
  rpnhma_webApplication:
    name: rpnhma_webApplication
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: rpnhma_practice

services:

  rpnhma_webApplication:
    image: rpnhma/forum
    container_name: rpnhma/forum
    build:
        context: .
        dockerfile: Dockerfile
    environment:

      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres

    networks:
      - rpnhma_webApplication
    ports:
      - "8080:8080"
    depends_on:
      - postgres



  postgres:
    image: postgres:14.1-alpine
    volumes:
      - postgres-data-rpnhma:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d

    user: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 5s
    networks:
      - rpnhma_webApplication
    hostname: postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "15432:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@base58.hr
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0

    networks:
      - rpnhma_webApplication

    depends_on:
      - postgres

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:alpine
    ports:
      - "9000:9000"

  keycloak:
    image: jboss/keycloak
    environment:
      - DB_VENDOR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak_user
      - DB_PASSWORD=keycloak_user
      - DB_PORT=5432
      - DB_SCHEMA=public
      - DB_ADDR=postgres
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin

    volumes:
      - postgres-data-rpnhma:/var/lib/postgresql/data

    ports:
      - "18080:8080"
    networks:
      - rpnhma_webApplication



